# Generated by Django 4.2.5 on 2023-10-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_renter_create_add_review_create_add_user_create_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_owner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
