# Generated by Django 4.2.5 on 2023-10-17 01:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleowner',
            name='foto1_dui',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
    ]
