# Generated by Django 4.2.5 on 2023-10-17 02:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_vehicleowner_foto1_dui_alter_userprofile_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleowner',
            name='foto2_dui',
            field=models.FileField(null=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='vehicleowner',
            name='foto_licencia',
            field=models.FileField(null=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='foto1_dui',
            field=models.FileField(null=True, upload_to=users.models.user_directory_path),
        ),
    ]
