# Generated by Django 4.2.5 on 2023-10-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_renter_create_add_alter_review_create_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='rental_price_hourly',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
