# Generated by Django 4.2.5 on 2023-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_vehicleowner_rental_price_hourly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='create_add',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='rental_price_daily',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
