# Generated by Django 4.2.5 on 2023-10-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_userprofile_is_owner_user_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='rental_price_daily',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='rental_price_hourly',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
