# Generated by Django 4.2.5 on 2023-10-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_vehicleowner_rental_price_daily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fecha_nacimeinto',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
