# Generated by Django 4.2.5 on 2023-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userprofile_apellido_userprofile_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_add',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
