# Generated by Django 4.2.5 on 2023-12-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_create_add_alter_user_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='availability_hours',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='rental_conditions',
            field=models.TextField(null=True),
        ),
    ]
