# Generated by Django 4.2.5 on 2023-10-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico de PayPal')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payments', to='transactions.transaction', verbose_name='Transacción asociada')),
            ],
            options={
                'verbose_name': 'Pago con PayPal',
                'verbose_name_plural': 'Pagos con PayPal',
            },
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=100, verbose_name='Nombre del titular de la tarjeta')),
                ('card_number', models.CharField(max_length=16, verbose_name='Número de tarjeta')),
                ('expiration_date', models.DateField(verbose_name='Fecha de expiración')),
                ('cvv', models.CharField(max_length=4, verbose_name='CVV')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_payments', to='transactions.transaction', verbose_name='Transacción asociada')),
            ],
            options={
                'verbose_name': 'Pago con Tarjeta de Crédito',
                'verbose_name_plural': 'Pagos con Tarjeta de Crédito',
            },
        ),
        migrations.CreateModel(
            name='BankTransferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=100, verbose_name='Nombre del titular de la cuenta')),
                ('account_number', models.CharField(max_length=20, verbose_name='Número de cuenta')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_payments', to='transactions.transaction', verbose_name='Transacción asociada')),
            ],
            options={
                'verbose_name': 'Transferencia Bancaria',
                'verbose_name_plural': 'Transferencias Bancarias',
            },
        ),
    ]
