# Generated by Django 4.2.5 on 2023-10-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferpayment',
            name='create_add',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='create_add',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='create_add',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='create_add',
            field=models.DateField(null=True),
        ),
    ]
