# Generated by Django 4.2.5 on 2023-11-04 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentmethod', '0002_banktransferpayment_create_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferpayment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
