# Generated by Django 4.2.5 on 2023-11-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0003_banktransferpayment_user_creditcardpayment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardpayment',
            name='typemethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paymentmethod.paymentmethod'),
        ),
    ]
