# Generated by Django 4.2.5 on 2023-11-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_create_add'),
        ('paymentmethod', '0004_creditcardpayment_typemethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardpayment',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_payments', to='transactions.transaction', verbose_name='Transacción asociada'),
        ),
    ]
