# Generated by Django 4.2.5 on 2023-11-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0005_alter_creditcardpayment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardpayment',
            name='expiration_date',
            field=models.CharField(max_length=5, verbose_name='Fecha de expiración'),
        ),
    ]
