# Generated by Django 4.2.5 on 2023-11-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_renter_bookings_and_more'),
        ('paymentmethod', '0006_alter_creditcardpayment_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransferpayment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_user', to='users.user'),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_user', to='users.user'),
        ),
    ]
