# Generated by Django 4.2.5 on 2023-11-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0007_alter_banktransferpayment_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcardpayment',
            options={},
        ),
    ]
