# Generated by Django 4.2.5 on 2023-11-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0008_alter_creditcardpayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardpayment',
            name='anio_expiracion',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='mes_expiracion',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
