# Generated by Django 4.2.5 on 2023-11-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0009_creditcardpayment_anio_expiracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardpayment',
            name='expiration_date',
        ),
    ]
