# Generated by Django 4.2.5 on 2023-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0010_remove_creditcardpayment_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardpayment',
            name='anio_expiracion',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='mes_expiracion',
            field=models.CharField(max_length=5),
        ),
    ]
