# Generated by Django 4.2.5 on 2023-10-04 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.renter'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
