# Generated by Django 4.2.5 on 2023-11-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_category_vehicle_category'),
        ('reviews', '0003_review_create_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_vehicle', to='vehicles.vehicle'),
        ),
    ]
