# Generated by Django 4.2.5 on 2023-10-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='combustible',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puertas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tipo_freno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='capacidad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
