# Generated by Django 4.2.5 on 2023-10-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_capacidad_vehicle_color_vehicle_combustible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='create_add',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='create_add',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='create_add',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='create_add',
            field=models.DateField(null=True),
        ),
    ]
