# Generated by Django 4.2.5 on 2023-10-17 01:23

from django.db import migrations, models
import vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_booking_create_add_location_create_add_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=vehicles.models.vehicle_directory_path)),
                ('create_add', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='create_add',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ManyToManyField(blank=True, to='vehicles.imagen'),
        ),
    ]
