# Generated by Django 4.2.5 on 2023-10-17 02:19

from django.db import migrations, models
import vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_imagen_alter_vehicle_create_add_remove_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='foto_tarjeta_circulacion_1',
            field=models.FileField(null=True, upload_to=vehicles.models.vehicle_directory_path),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='foto_tarjeta_circulacion_2',
            field=models.FileField(null=True, upload_to=vehicles.models.vehicle_directory_path),
        ),
    ]
