# Generated by Django 4.2.5 on 2023-10-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_imagen_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='canton',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='departamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='referencia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
