# Generated by Django 4.2.5 on 2023-10-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_location_canton_location_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='transmision',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
