# Generated by Django 4.2.5 on 2023-10-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicle_transmision'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='kilometraje',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
