# Generated by Django 4.2.5 on 2023-10-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_kilometraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='create_add',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
