# Generated by Django 4.2.5 on 2023-11-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_remove_seguro_vehicle_vehicle_seguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='seguro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='vehicles.seguro'),
        ),
    ]
