# Generated by Django 4.2.5 on 2023-11-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_alter_vehicle_seguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price_hourly',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
