# Generated by Django 4.2.5 on 2023-11-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_alter_imagen_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pais',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
