# Generated by Django 4.2.5 on 2023-11-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
