# Generated by Django 4.2.5 on 2023-11-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
