# Generated by Django 4.2.5 on 2023-11-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_create_add'),
        ('locations', '0003_location_estado'),
    ]

    operations = [
    ]
