# Generated by Django 4.2.5 on 2023-11-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_descuento_booking_codigo_reserva_booking_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='codigo_reserva',
        ),
    ]
