# Generated by Django 4.2.5 on 2023-11-13 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0006_alter_creditcardpayment_expiration_date'),
        ('bookings', '0005_remove_booking_codigo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymentmethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metodo_pago', to='paymentmethod.paymentmethod'),
        ),
    ]
