# Generated by Django 4.2.5 on 2023-11-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_qr_code_booking_url_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_transaction_wompi',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
