# Generated by Django 4.2.5 on 2023-11-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_id_transaction_wompi'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='esta_productivo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_enlace',
            field=models.IntegerField(null=True),
        ),
    ]
