# Generated by Django 4.2.5 on 2023-11-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_esta_productivo_booking_id_enlace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='url_qr_code_enlace',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='url_enlace',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
